package net.royling.lunchboxsustenanceproject.datagen;

import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.client.model.generators.ItemModelProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.royling.lunchboxsustenanceproject.LunchboxSustenanceProject;
import net.royling.lunchboxsustenanceproject.ModItems;

public class ModItemModelProvider extends ItemModelProvider {
    public ModItemModelProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output, LunchboxSustenanceProject.MODID, existingFileHelper);
    }

    @Override
    protected void registerModels() {
        basicItem(ModItems.FAILED_CONCOCTION.get());
        basicItem(ModItems.FRUIT_ICON.get());
        basicItem(ModItems.SUGAR_ICON.get());
        basicItem(ModItems.NOT_EAT_ICON.get());
        basicItem(ModItems.MAGIC_ICON.get());
        basicItem(ModItems.ENDER_ICON.get());
        basicItem(ModItems.VEGETABLE_ICON.get());
        basicItem(ModItems.MONSTER_ICON.get());
        basicItem(ModItems.ICE_ICON.get());
        basicItem(ModItems.MEAT_ICON.get());
        basicItem(ModItems.FISH_ICON.get());
        basicItem(ModItems.CEREALS_ICON.get());
        basicItem(ModItems.EGG_ICON.get());
        basicItem(ModItems.MILK_ICON.get());
        basicItem(ModItems.SEED_ICON.get());
        basicItem(ModItems.MUSHROOM_ICON.get());
        basicItem(ModItems.BACON_AND_EGGS.get());
        basicItem(ModItems.APPLE_PIE.get());
        basicItem(ModItems.GOLDEN_APPLE_PIE.get());
        basicItem(ModItems.FISH_ROLL.get());
        basicItem(ModItems.FRIED_FISH.get());
        basicItem(ModItems.JAM.get());
        basicItem(ModItems.RABBIT_SANDWICH.get());
        basicItem(ModItems.FRUIT_SALAD.get());
        basicItem(ModItems.HONEY_GLAZED_HAM.get());
        basicItem(ModItems.HONEY_GLAZED_PORK.get());
        basicItem(ModItems.MEAT_SKEWER.get());
        basicItem(ModItems.MEATBALL.get());
        basicItem(ModItems.MEAT_SOUP.get());
        basicItem(ModItems.MONSTER_LASAGNA.get());
        basicItem(ModItems.EGG_DUMPLING.get());
        basicItem(ModItems.PUMPKIN_COOKIE.get());
        basicItem(ModItems.STIR_FRY.get());
        basicItem(ModItems.STUFFED_POTATO.get());
        basicItem(ModItems.TOFFEE.get());
        basicItem(ModItems.TURKEY_DINNER.get());
        basicItem(ModItems.COD_DISH.get());
        basicItem(ModItems.WAFFLE.get());
        basicItem(ModItems.WATERMELON_POPSICLE.get());
        basicItem(ModItems.MIXED_NUTS.get());
        basicItem(ModItems.ICE_CREAM.get());
        basicItem(ModItems.FLOWER_SALAD.get());
        basicItem(ModItems.STIR_FRIED_PORK.get());
        basicItem(ModItems.SEAFOOD_BISQUE.get());
        basicItem(ModItems.CEVICHE.get());
        basicItem(ModItems.CALIFORNIA_ROLL.get());
        basicItem(ModItems.SURF_AND_TURF.get());
        basicItem(ModItems.RAINBOW_CANDY.get());
        basicItem(ModItems.APPLE_JELLY.get());
        basicItem(ModItems.CARROT_SOUP.get());
        basicItem(ModItems.MEAT_BUN.get());
        basicItem(ModItems.FRESH_SALSA.get());
        basicItem(ModItems.CREAMED_POTATOES.get());
        basicItem(ModItems.POTATO_TOWER.get());
        basicItem(ModItems.VEGETABLE_COCKTAIL.get());
        basicItem(ModItems.MONSTER_TARTARE.get());
        basicItem(ModItems.FRESH_FRUIT_CREPE.get());
        basicItem(ModItems.BONE_SOUP.get());
        basicItem(ModItems.GLOW_BERRY_MOUSSE.get());
        basicItem(ModItems.SEAFOOD_CHOWDER.get());
        basicItem(ModItems.BLAZE_JELLY.get());
        basicItem(ModItems.FLUFFY_POTATO_SOUFFLE.get());
        basicItem(ModItems.LOBSTER_DINNER.get());
        basicItem(ModItems.LOBSTER_SOUP.get());
        basicItem(ModItems.STUFFED_FISH_HEAD.get());
        basicItem(ModItems.BARNACLE_PITA.get());
        basicItem(ModItems.BARNACLE_LINGUINE.get());
        basicItem(ModItems.BARNACLE_SUSHI.get());
        basicItem(ModItems.TOMATO_SCRAMBLED_EGGS.get());
        basicItem(ModItems.LOBSTER.get());
        basicItem(ModItems.COOKED_LOBSTER.get());
        basicItem(ModItems.BARNACLE.get());
        basicItem(ModItems.COOKED_BARNACLE.get());
        basicItem(ModItems.BUTTER.get());
        basicItem(ModItems.COOKING_POT.get());
        basicItem(ModItems.COOKED_SEA_CUCUMBER.get());
        basicItem(ModItems.SEA_CUCUMBER.get());
        basicItem(ModItems.SMALL_HALIBUT.get());
        basicItem(ModItems.COOKED_SMALL_HALIBUT.get());
        basicItem(ModItems.HALIBUT.get());
        basicItem(ModItems.COOKED_HALIBUT.get());
        basicItem(ModItems.TUNA.get());
        basicItem(ModItems.COOKED_TUNA.get());
        basicItem(ModItems.EEL.get());
        basicItem(ModItems.COOKED_EEL.get());
        basicItem(ModItems.PIKE.get());
        basicItem(ModItems.COOKED_PIKE.get());
        basicItem(ModItems.TILAPIA.get());
        basicItem(ModItems.COOKED_TILAPIA.get());
        basicItem(ModItems.COOKED_HERRING.get());
        basicItem(ModItems.HERRING.get());
        basicItem(ModItems.COOKED_CATFISH.get());
        basicItem(ModItems.CATFISH.get());
        basicItem(ModItems.GROUPER.get());
        basicItem(ModItems.COOKED_GROUPER.get());
        basicItem(ModItems.BLACK_SEABREAM.get());
        basicItem(ModItems.COOKED_BLACK_SEABREAM.get());
        basicItem(ModItems.SEAHORSE.get());
        basicItem(ModItems.COOKED_SEAHORSE.get());
        basicItem(ModItems.COOKED_SARDINE.get());
        basicItem(ModItems.SARDINE.get());
        basicItem(ModItems.COOKED_SILVERFISH.get());
        basicItem(ModItems.SILVERFISH.get());
        basicItem(ModItems.COOKED_BASS.get());
        basicItem(ModItems.BASS.get());
        basicItem(ModItems.COOKED_OCTOPUS.get());
        basicItem(ModItems.OCTOPUS.get());
        basicItem(ModItems.COOKED_JELLYFISH.get());
        basicItem(ModItems.JELLYFISH.get());
        basicItem(ModItems.STURGEON.get());
        basicItem(ModItems.COOKED_STURGEON.get());
        basicItem(ModItems.BREAM.get());
        basicItem(ModItems.COOKED_BREAM.get());
        basicItem(ModItems.SHRIMP.get());
        basicItem(ModItems.COOKED_SHRIMP.get());
        basicItem(ModItems.CRAB.get());
        basicItem(ModItems.COOKED_CRAB.get());

    }
}
